spring:
    application:
        name: main

    r2dbc:
        url: r2dbc:postgresql://localhost:5432/gatewaydb
        username: siva
        password: 1664

    sql:
        init:
            mode: never
